# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    post_create_environment:
    # Install poetry      
    - pip install poetry      
    # Tell poetry to not use a virtual environment
    - poetry config virtualenvs.create false    
    post_install:
    # Install dependencies
    - poetry install --with docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf


mkdocs:
  configuration: docs/mkdocs.yml
  fail_on_warning: false

python:
  install:
  - requirements: docs/requirements.txt